### PR TITLE
fix: uploader webkitdirectory type

### PR DESCRIPTION
**Pull request by feiyan-Nan**
修复uploader组件的webkitdirectory属性的类型
根据MDN文档 https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLInputElement/webkitdirectory
webkitdirectory是boolean类型

## Types of changes

- [ ] New feature
- [x] Bug fix
- [ ] Documentation change
- [ ] Coding style change
- [ ] Component style change
- [ ] Refactoring
- [ ] Performance improvement
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others 

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|     Uploader      |      修复uploader组件的`webkitdirectory`属性的类型         |      Fix the type of the `webkitdirectory` attribute of the uploader component         |                |

## Checklist:

- [x] Test suite passes (`npm run test`)
- [x] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [x] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)

### CODE REVIEW

**Comment by PengJiyuan** [comment]
麻烦更新一下快照 `yarn run test:client -u`

**Comment by yinkaihui** [comment]
你好，需要更新快照。 以及 changelog 可以参考其他 bug 修复的 pr 调整一下～ 辛苦～❤️

**Comment by feiyan-Nan** [comment]
> 麻烦更新一下快照 `yarn run test:client -u`

你好, 我运行了这个命令, 并没有更新快照

**Comment by yinkaihui** [comment]
先执行下 yarn build:cjs ，然后再更新快照

**Comment by feiyan-Nan** [comment]
为啥改为true, 就不生效了呢

**Comment by feiyan-Nan** [comment]
改为字符串的true

**Pull request merged**
