### PR TITLE
Style: add Image footer bottom border radius

### PR DESCRIPTION
**Pull request by slevisp**
Add overflow: hidden to arco-image, to prevent footer bottom border radius overflow, when set large border radius.
增加overflow: hidden给arco-image，防止当圆角被设置为大圆角时，footer底部圆角溢出。
## Types of changes

- [ ] New feature
- [ ] Bug fix
- [ ] Enhancement
- [ ] Documentation change
- [ ] Coding style change
- [x] Component style change
- [ ] Refactoring
- [ ] Test cases
- [ ] Continuous integration
- [ ] Typescript definition change
- [ ] Breaking change
- [ ] Others 

## Changelog

| Component | Changelog(CN) | Changelog(EN) | Related issues |
| --------- | ------------- | ------------- | -------------- |
|Image| 修复 `Image` 组件`border-radius`较大时，`footer` 区域底部圆角溢出的样式问题。|Fixed a style issue where the bottom corners of the `footer` area overflow when the `border-radius` of the `Image` component is large.|                |

## Checklist:

- [ ] Test suite passes (`npm run test`)
- [ ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)

### CODE REVIEW

**Comment by yinkaihui** [comment]
这个地方是不是让 footer 继承下 arco-image 的就好，无需引入 overflow: hidden 属性 ？

**Comment by slevisp** [comment]
> 
是的，把overflow: hidden 拿掉了，让footer的bottom圆角继承了arco-image的

**Comment by yinkaihui** [comment]
> 是的，把overflow: hidden 拿掉了，让footer的bottom圆角继承了arco-image的

加错地方了， 需要加到 `..arco-image-with-footer-inner .arco-image-footer` 下，footer 有两种形式，https://arco.design/react/components/image#%E6%98%BE%E7%A4%BA-Caption

**Comment by slevisp** [comment]
> > 是的，把overflow: hidden 拿掉了，让footer的bottom圆角继承了arco-image的
> 
> 加错地方了， 需要加到 `..arco-image-with-footer-inner .arco-image-footer` 下，footer 有两种形式，https://arco.design/react/components/image#%E6%98%BE%E7%A4%BA-Caption

已修改

**Review by yinkaihui — APPROVED** [review]

**Pull request merged**
